apiVersion: v2
name: opa-notary-connector
description: OPA Notary Connector helm chart
type: application
version: 0.1.2
appVersion: 0.1.2

dependencies:
  - name: opa
    version: 1.14.6
    repository: "https://open-policy-agent.github.io/kube-mgmt/charts"
