apiVersion: v2
name: opa-notary-connector
description: OPA Notary Connector helm chart
type: application
version: 0.1.0-rc5
appVersion: 0.1.0-rc5

dependencies:
  - name: opa
    version: 1.14.4
    repository: https://kubernetes-charts.storage.googleapis.com
